M48
; DRILL file KiCad 10.0.4 date 2026-10-09T22:51:58
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-09T22:51:58+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,8,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C2.200
%
G90
G05
T1
X23.11Y5.2
X28.89Y5.2
T2
X28.936Y-36.154
T3
X23.91Y-53.2
X28.99Y-52.184
X28.99Y-54.216
T4
X-0.15Y7.184
X0.6Y2.188
M30
